/*
USE MASTER
DROP DATABASE AUTO_CLEAN
*/
CREATE DATABASE AUTO_CLEAN
GO
USE AUTO_CLEAN
GO
CREATE TABLE CLIENT
(
CLIENT_ID	INT  IDENTITY PRIMARY KEY,
NAME		varchar(20),
VORNAME		varchar(20),
LASTNAME	varchar(20),
NUMBER		varchar(11),
VER			ROWVERSION
)

CREATE TABLE WORKER
(
WORKER_ID	INT IDENTITY PRIMARY KEY,
NAME		varchar(20),
VORNAME		varchar(20),
LASTNAME	varchar(20),
NUMBER		varchar(11),
EXPER		tinyint,
WORK		varchar(20),
WORKTIME	varchar(20),
VER			ROWVERSION
)

CREATE TABLE CAR
(
CAR_ID		INT IDENTITY PRIMARY KEY,
MARK		VARCHAR(20),
WIDTH		FLOAT,
HEIGHT		FLOAT,
NUMBER		VARCHAR(10),
COLOR		VARCHAR(20),
VER			ROWVERSION
)

CREATE TABLE LIST
(
LIST_ID		INT IDENTITY PRIMARY KEY,
DATE_WORK	DATE,
ID_CLIENT	INT FOREIGN KEY REFERENCES  AUTO_CLEAN.DBO.CLIENT(CLIENT_ID),
ID_WORKER	INT FOREIGN KEY REFERENCES  AUTO_CLEAN.DBO.WORKER(WORKER_ID),
ID_CAR		INT FOREIGN KEY REFERENCES  AUTO_CLEAN.DBO.CAR(CAR_ID),
WORK_TYPE	VARCHAR(30),
COST		INT,
VER			ROWVERSION
)

INSERT INTO CLIENT (NAME,VORNAME,LASTNAME,NUMBER) VALUES
('Аслан','Кудайберген','Оралбаев','87773426455')
INSERT INTO CLIENT (NAME,VORNAME,LASTNAME,NUMBER) VALUES
('Бекарыс','Кудайберген','Оралбаев','87773429444')
INSERT INTO CLIENT (NAME,VORNAME,LASTNAME,NUMBER) VALUES
('Айгул','Кудайберген','Оралбаевна','87773429455')

INSERT INTO WORKER (NAME,VORNAME,LASTNAME,NUMBER,EXPER,WORK,WORKTIME) VALUES
('Иван','Кудайберген','Оралбаевна','87773429864',12,'Чистка салона','9:00-18:00')
INSERT INTO WORKER (NAME,VORNAME,LASTNAME,NUMBER,EXPER,WORK,WORKTIME) VALUES
('Алексей','Кудайберген','Оралбаевна','87773429864',12,'Чистка чехлов','9:00-18:00')
INSERT INTO WORKER (NAME,VORNAME,LASTNAME,NUMBER,EXPER,WORK,WORKTIME) VALUES
('Дима','Кудайберген','Оралбаевна','87773429864',12,'Чистка багажника','9:00-18:00')

INSERT INTO CAR (MARK,WIDTH,HEIGHT,NUMBER,COLOR) VALUES
('Toyota Camry 70',5,2.3,'A324DSM','Синий')
INSERT INTO CAR (MARK,WIDTH,HEIGHT,NUMBER,COLOR) VALUES
('Toyota Camry 35',5,2.3,'A334DSM','белый')
INSERT INTO CAR (MARK,WIDTH,HEIGHT,NUMBER,COLOR) VALUES
('Toyota Camry 50',5,2.3,'A344DSM','черный')

INSERT INTO LIST (DATE_WORK,ID_CLIENT,ID_WORKER,ID_CAR,WORK_TYPE,COST) VALUES
('2021-06-15',1,2,3,'Чистка салона',6000)
INSERT INTO LIST (DATE_WORK,ID_CLIENT,ID_WORKER,ID_CAR,WORK_TYPE,COST) VALUES
('2021-05-10',2,3,1,'Чистка чехлов',6000)
INSERT INTO LIST (DATE_WORK,ID_CLIENT,ID_WORKER,ID_CAR,WORK_TYPE,COST) VALUES
('2021-04-08',3,1,2,'Чистка багажника',6000)